<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>ICSharpCode.NRefactory.CSharp</AssemblyName>
    <RootNamespace>ICSharpCode.NRefactory.CSharp</RootNamespace>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);FULL_AST</DefineConstants>
    
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591,1587,1570</NoWarn>

    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\ICSharpCode.NRefactory.snk</AssemblyOriginatorKeyFile>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\cecil\Mono.Cecil.csproj" />
    <ProjectReference Include="..\ICSharpCode.NRefactory.Cecil\ICSharpCode.NRefactory.Cecil.csproj" />
    <ProjectReference Include="..\ICSharpCode.NRefactory\ICSharpCode.NRefactory.csproj" />
  </ItemGroup>

<!--  <ItemGroup>-->
<!--    <PackageReference Include="System.CodeDom" Version="4.7.0" />-->
<!--  </ItemGroup>-->

</Project>