<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>ICSharpCode.NRefactory.Cecil</AssemblyName>
    <RootNamespace>ICSharpCode.NRefactory.Cecil</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\ICSharpCode.NRefactory.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ICSharpCode.NRefactory\ICSharpCode.NRefactory.csproj">
      <Project>{3B2A5653-EC97-4001-BB9B-D90F1AF2C371}</Project>
      <Name>ICSharpCode.NRefactory</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\cecil\Mono.Cecil.csproj">
      <Project>{D68133BD-1E63-496E-9EDE-4FBDBF77B486}</Project>
      <Name>Mono.Cecil</Name>
    </ProjectReference>
  </ItemGroup>

</Project>